### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by bobleegogogo** [GIScience/ohsome2label#1]
when running for large-sccale image download, one might come up with an **requests.exceptions.ConnectionError**

Error message: 

requests.exceptions.ConnectionError: HTTPConnectionPool(host='t0.tiles.virtualearth.net', port=80): Max retries exceeded with url: /tiles/a12020330203220030.png?g=854&mkt=en-US&token=your_token(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff69bf7ecf8>: Failed to establish a new connection: [Errno 110] Connection timed out',))
44%|███████████████████████ | 11394/26174 [15:14<19:45, 12.47it/s]

Potential solution: 

add request status check and random sleep

**Comment by wuzyzy** [comment]
> when running for large-sccale image download, one might come up with an **requests.exceptions.ConnectionError**
> 
> Error message:
> 
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='t0.tiles.virtualearth.net', port=80): Max retries exceeded with url: /tiles/a12020330203220030.png?g=854&mkt=en-US&token=your_token(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff69bf7ecf8>: Failed to establish a new connection: [Errno 110] Connection timed out',))
> 44%|███████████████████████ | 11394/26174 [15:14<19:45, 12.47it/s]
> 
> Potential solution:
> 
> add request status check and random sleep

Notice not to put your token in your issue. I just modified it for you.
Please put your config. I will reproduce your error and fix it.

**Comment by bobleegogogo** [comment]
> 
> 
> > when running for large-sccale image download, one might come up with an **requests.exceptions.ConnectionError**
> > Error message:
> > requests.exceptions.ConnectionError: HTTPConnectionPool(host='t0.tiles.virtualearth.net', port=80): Max retries exceeded with url: /tiles/a12020330203220030.png?g=854&mkt=en-US&token=your_token(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff69bf7ecf8>: Failed to establish a new connection: [Errno 110] Connection timed out',))
> > 44%|███████████████████████ | 11394/26174 [15:14<19:45, 12.47it/s]
> > Potential solution:
> > add request status check and random sleep
> 
> Notice not to put your token in your issue. I just modified it for you.
> Please put your config. I will reproduce your error and fix it.


Here is the config I used:

project:
  name: DE_wastewater
  workspace: ./DE_wastewater
  project_time: 2020-07-21
  task: segmentation

osm:
  api: ohsome
  url: https://api.ohsome.org/v1/elements/geometry
  bboxes: [5.872,47.270,15.038,55.057]
  tags:
    - {'label': 'wastewater', 'key': 'man_made', 'value': 'wastewater_plant'}

  timestamp: 2019-10-20
  types: polygon

image:
  img_api: bing
  img_url: http://t0.tiles.virtualearth.net/tiles/a{q}.png?g=854&mkt=en-US&token={token}
  api_token : ''
  zoom: 17

**Comment by wuzyzy** [comment]
> > > when running for large-sccale image download, one might come up with an **requests.exceptions.ConnectionError**
> > > Error message:
> > > requests.exceptions.ConnectionError: HTTPConnectionPool(host='t0.tiles.virtualearth.net', port=80): Max retries exceeded with url: /tiles/a12020330203220030.png?g=854&mkt=en-US&token=your_token(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff69bf7ecf8>: Failed to establish a new connection: [Errno 110] Connection timed out',))
> > > 44%|███████████████████████ | 11394/26174 [15:14<19:45, 12.47it/s]
> > > Potential solution:
> > > add request status check and random sleep
> > 
> > 
> > Notice not to put your token in your issue. I just modified it for you.
> > Please put your config. I will reproduce your error and fix it.
> 
> Here is the config I used:
> 
> project:
> name: DE_wastewater
> workspace: ./DE_wastewater
> project_time: 2020-07-21
> task: segmentation
> 
> osm:
> api: ohsome
> url: https://api.ohsome.org/v1/elements/geometry
> bboxes: [5.872,47.270,15.038,55.057]
> tags:
> - {'label': 'wastewater', 'key': 'man_made', 'value': 'wastewater_plant'}
> 
> timestamp: 2019-10-20
> types: polygon
> 
> image:
> img_api: bing
> img_url: [http://t0.tiles.virtualearth.net/tiles/a{q}.png?g=854&mkt=en-US&token={token}](http://t0.tiles.virtualearth.net/tiles/a%7Bq%7D.png?g=854&mkt=en-US&token=%7Btoken%7D)
> api_token : ''
> zoom: 17

Fixed. See ff3a50da9db2fd90637226a02eda4e6f939a8790.
If it works, please close the issue.

**Comment by bobleegogogo** [comment]
thanks, the issue is fixed
