### ISSUE TITLE
Copy-paste error in readme

### ISSUE THREAD

**Issue by KowatschFab** [GIScience/ohsome2label#2]
Hey, I just flew over your readme and it seems like there happened some sort of formatting or copy-past error in your readme. In the section about "Command line functions", it seems the text that follows is also somehow formatted as a headline and appears twice.

**Comment by wuzyzy** [comment]
> Hey, I just flew over your readme and it seems like there happened some sort of formatting or copy-past error in your readme. In the section about "Command line functions", it seems the text that follows is also somehow formatted as a headline and appears twice.

Thank you for your reminder! I have deleted the duplicate part.
